#!/usr/bin/env bash

# external scripts

REAL_USER="${SUDO_USER:-$USER}"
REAL_HOME=$(getent passwd "$REAL_USER" | cut -d: -f6)
ROOT="$REAL_HOME/.cargopp"
#USERROOT=$(pwd)
source "$ROOT"/bin/lib/paint
run_necessary_build() {
  local src=$(stat -c "%Y" src)
  local cmkl=$(stat -c "%Y" CMakeLists.txt)
  local build=$(stat -c "%Y" build)
  if [[ "$src" -gt "$build" || "$cmkl" -gt "$build" ]]; then
    echo true
  else
    echo false
  fi
}
build_everygood() {
  echo -e "${GREEN}build is up to date ${NC}" >&2
}

build_cargopp() {
  if [[ -d "build" && -f "CMakeLists.txt" && -d "src" ]]; then
    necessary_build=$(run_necessary_build)
    if [[ "$necessary_build" == true ]]; then
      echo -e "${GREEN}🔨 Building project...${NC}"
      cmake -B build
      cmake --build build
    else
      build_everygood
    fi
  else
    echo -e "${RED}CMakeLists not found."
    echo -e "<Use: ${BLUE}cargopp --help --build>${NC}to see how to use cargopp build"
  fi
}
