#! usr/bin/env bash

run_cargopp() {
  local name=$1 # start compilation

  build_cargopp
  if [ ! -f "build/$name" ]; then
    echo "❌ Error: Build/$name does not exist. Note: if you want to run main do 'cargopp run <project name>'."
    exit 1
  fi

  ./build/"$name"

}
