#!/bin/bash
set -euo pipefail
# ---- COULEURS ANSI ----
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# cargopp check_dependencies

check_dependencies_cargopp() {
  echo "🔍 Checking dependencies..."
  local os="$1"
  local missing_deps=()
  local curl_absent=false
  if ! command -v cmake &>/dev/null; then missing_deps+=("cmake"); fi
  if ! command -v g++ &>/dev/null && ! command -v gcc &>/dev/null; then missing_deps+=("g++"); fi
  if ! command -v curl >/dev/null 2>&1; then curl_absent=true; fi

  # stop if everythink is good

  if [ "${#missing_deps[@]}" -eq 0 ] && [ "$curl_absent" == false ]; then
    return 0
  else
    if [ "$curl_absent" == true ]; then
      case "$os" in
      *redhat*)
        install_curl="sudo dnf install curl"
        ;;
      *debian*)
        install_curl="sudo apt install curl"
        ;;
      *)
        echo -e "${RED}❌ Unsupported OS template. You can install cmake and g++ manually.${NC}"
        exit 1
        ;;
      esac
    else
      install_curl=""
    fi

    if [ ! "${#missing_deps[@]}" -eq 0 ]; then
      echo -e "${YELLOW}⚠️ Missing required tools: ${missing_deps[*]}${NC}"
      local install_cmd=""
      case "$os" in
      *debian*)
        install_cmd="sudo apt update && sudo apt install -y cmake build-essential"
        ;;
      *redhat*)
        install_cmd="sudo dnf update -y && sudo dnf group install -y 'Development Tools' && sudo dnf install -y cmake"
        ;;
      *)
        echo -e "${RED}❌ Unsupported OS template. You can install cmake and g++ manually.${NC}"
        exit 1
        ;;
      esac
      if [ ! -z "$install_curl" ]; then
        install_cmd="$install_cmd && $install_curl"
      fi
    else
      install_cmd="$install_curl"
    fi

    echo -e "${BLUE}👉 cargopp can install them for you.${NC}"
    read -p "Do you want to run [ $install_cmd ] ? (Y/n): " response
    response=${response,,} # Convert to lowercase

    if [[ "$response" =~ ^(yes|y|"") ]]; then
      echo -e "${BLUE}⚙️ Installing dependencies...${NC}"
      eval "$install_cmd"
      if [ $? -ne 0 ]; then
        echo -e "${RED}❌ Error during dependencies installation.${NC}"
        exit 1
      fi
      echo -e "${GREEN}✅ Dependencies installed successfully!${NC}"
    else
      echo -e "${RED}❌ Installation aborted. cargopp requires cmake and g++ to work.${NC}"
      exit 1
    fi
  fi

}

find_os_familly() {

  if [[ "$OSTYPE" == "darwin"* ]]; then
    OS_FAMILY="macos"

  elif command -v apt >/dev/null 2>&1; then
    OS_FAMILY="debian"

  elif command -v dnf >/dev/null 2>&1; then
    OS_FAMILY="redhat"

  elif command -v pacman >/dev/null 2>&1; then
    OS_FAMILY="arch"

  elif command -v zypper >/dev/null 2>&1; then
    OS_FAMILY="suse"

  else
    OS_FAMILY="unknown"
  fi

  echo "$OS_FAMILY"
}
search_cargopp_and_kill() {
  victim=$(which cargopp)
  if [ ! -z "$victim" ]; then
    echo -e "${RED} a software at the name cargopp is detected ${NC}"
    echo -e "${RED} cargopp want to remove it before installation"
    echo -e "${BLUE} Do you allow cargopp remove it ?.${NC}"
    read -p "Do you allow cargopp remove it ? (Y/n): " response
    response=${response,,} # Convert to lowercase

    if [[ "$response" =~ ^(yes|y|"") ]]; then
      sudo rm -f $victim
    else
      echo -e "${RED}❌ Installation aborted. "
      exit 1
    fi
  fi
}
install_skeleton() {
  mkdir -p .cargopp/bin/lib/help/commands
  mkdir -p .cargopp/bin/lib/smart_update/tools
  mkdir -p .cargopp/.cache
}
install_curl_bring() {
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/new_c -o new_c && chmod +x new_c
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/new_cpp -o new_cpp && chmod +x new_cpp
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/build_cargopp -o build_cargopp && chmod +x build_cargopp
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/run -o run && chmod +x run
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/clean -o clean && chmod +x clean
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/linux/setup/uninstall -o uninstall && chmod +x uninstall
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/paint -o paint && chmod +x paint
  cd smart_update
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/linux/smart_update/fly -o fly && chmod +x fly
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/linux/smart_update/update -o update && chmod +x update
  cd tools
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/linux/smart_update/tools/check_dependencies -o check_dependencies && chmod +x check_dependencies
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/linux/smart_update/tools/curl_bring -o curl_bring && chmod +x curl_bring
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/linux/smart_update/tools/find_os -o find_os && chmod +x find_os

  cd .. # go to smart_update
  cd .. # go to lib
  cd help
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/help/help -o help && chmod +x help
  cd commands
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/help/commands/commands -o commands && chmod +x commands
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/help/commands/run_cmd -o run_cmd && chmod +x run_cmd
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/help/commands/build_cmd -o build_cmd && chmod +x build_cmd
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/help/commands/clean_cmd -o clean_cmd && chmod +x clean_cmd
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/lib/help/commands/cmakelist_cmd -o cmakelist_cmd && chmod +x cmakelist_cmd
  cd .. #go to help
  cd .. # go to lib
  #install cargopp from git and make his folder global
  cd .. # go to bin

  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/src/cargopp -o cargopp && chmod +x cargopp
  #position=$(pwd)
  #echo 'export PATH="$PATH:$position"' >>~/.bashrc
  #sudo ln -sfn "$REAL_HOME/.cargopp/bin/cargopp" /usr/local/bin/cargopp
  cd .. # go to .cargopp
  #install version
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/cargopp_version -o cargopp_version && chmod +r cargopp_version
  cd .cache
  curl -fsSL https://raw.githubusercontent.com/gabyx540ya/cargopp/main/.cache/version -o version && chmod +r version
  cd .. # go to .cargopp
  cd bin/lib
}
manage_installation_deb_redhat() {
  echo "Installation of cargopp In the system.."
  if [ "$EUID" -ne 0 ]; then
    echo "Error: you must execute 'sudo ./install to install cargopp"
    exit 1
  fi
  # chech dependencies

  check_dependencies_cargopp "$1"
  # create the repertorie .cargopp
  last_position=$(pwd)
  REAL_USER="${SUDO_USER:-$USER}"
  REAL_HOME=$(getent passwd "$REAL_USER" | cut -d: -f6)
  cd "$REAL_HOME"
  if [[ -d .cargopp ]]; then
    rm -rf .cargopp && mkdir .cargopp
  fi
  install_skeleton
  # installing git repositories
  echo "⚙️ installing git repositories of cargopp.."
  cd .cargopp/bin
  cd lib
  # search the cargopp and kill it
  search_cargopp_and_kill
  install_curl_bring
  sudo ln -sfn "$REAL_HOME/.cargopp/bin/cargopp" /usr/local/bin/cargopp
  cd .. # go to .cargopp
  cd $last_position
  rm -- "$(basename "$0")" >/dev/null 2>&1
  echo "cargopp installed with success!"
  exit 0
}

# cargopp install
OS=$(find_os_familly)
case "$OS" in
*debian*)
  manage_installation_deb_redhat "$OS"
  ;;
*redhat*)
  manage_installation_deb_redhat "$OS"
  ;;
*)
  echo -e "${RED}❌ Unsupported OS template. Please install cmake and g++ manually.${NC}"
  exit 1
  ;;
esac
