#!/bin/bash

# ---- COULEURS ANSI ----
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

find_os_familly() {

  if [[ "$OSTYPE" == "darwin"* ]]; then
    OS_FAMILY="macos"

  elif command -v apt >/dev/null 2>&1; then
    OS_FAMILY="debian"

  elif command -v dnf >/dev/null 2>&1; then
    OS_FAMILY="redhat"

  elif command -v pacman >/dev/null 2>&1; then
    OS_FAMILY="arch"

  elif command -v zypper >/dev/null 2>&1; then
    OS_FAMILY="suse"

  else
    OS_FAMILY="unknown"
  fi

  echo "$OS_FAMILY"
}

# cargopp check_dependencies

check_dependencies_cargopp() {
  echo "🔍 Checking dependencies..."
  local os=$(find_os_familly)
  local missing_deps=()

  if ! command -v cmake &>/dev/null; then missing_deps+=("cmake"); fi
  if ! command -v g++ &>/dev/null && ! command -v clang++ &>/dev/null; then missing_deps+=("g++"); fi

  # stop if everythink is good

  if [ ${#missing_deps[@]} -eq 0 ]; then
    return 0
  fi
  echo -e "${YELLOW}⚠️ Missing required tools: ${missing_deps[*]}${NC}"

  #
  local install_cmd=""
  case "$os" in
  *debian*)
    install_cmd="sudo apt update && sudo apt install -y cmake build-essential"
    ;;
  *arch*)
    install_cmd="sudo pacman -Sy --noconfirm cmake base-devel"
    ;;
  *suse*)
    install_cmd="sudo zypper install -y cmake gcc-c++ make"
    ;;
  *macos*)
    install_cmd="brew install cmake"
    ;;
  *)
    echo -e "${RED}❌ Unsupported OS template. Please install cmake and g++ manually.${NC}"
    exit 1
    ;;
  esac
  echo -e "${BLUE}👉 cargopp can install them for you.${NC}"
  read -p "Do you want to run [ $install_cmd ] ? (Y/n): " response
  response=${response,,} # Convert to lowercase

  if [[ "$response" =~ ^(yes|y|"") ]]; then
    echo -e "${BLUE}⚙️ Installing dependencies...${NC}"
    eval "$install_cmd"
    if [ $? -ne 0 ]; then
      echo -e "${RED}❌ Error during dependencies installation.${NC}"
      exit 1
    fi
    echo -e "${GREEN}✅ Dependencies installed successfully!${NC}"
  else
    echo -e "${RED}❌ Installation aborted. cargopp requires cmake and g++ to work.${NC}"
    exit 1
  fi
}

# cargopp install

install_cargopp() {
  #it work on linux

  echo "Installation of cargopp In the system.."
  if [ "$EUID" -ne 0 ]; then
    echo "Error: you must execute 'sudo ./cargopp to install cargopp"
    exit 1
  fi
  # chech dependencies

  check_dependencies_cargopp
  #copy the file to global path

  cp "$0" /usr/local/bin/cargopp
  #make cargopp executable

  chmod +x /usr/local/bin/cargopp

  echo "cargopp installed with success!"
  exit 0

}
#cargopp build

build_cargopp() {
  echo "🔨 Building project..."
  cmake -B build
  cmake --build build
  echo "💡 Note: if you have src/bin files to compile,"
  echo "please notice them in CMakeLists.txt by doing for example:"
  echo "add_executable(prog src/bin/prog.cpp)"
}
#cargopp new

new_cargopp() {
  local name="$1"

  if [ -z "$name" ]; then
    echo "❌ Error: Please specify a project name. Usage: cargopp new <project_name>"
    exit 1
  fi

  if [ -d "$name" ]; then
    echo "Error : Directory '$name' already exists."
    exit 1
  fi

  mkdir -p "$name/src"
  mkdir -p "$name/build"
  # main.cpp generation

  cat >"$name/src/main.cpp" <<EOF
  #include <iostream>

  int main()
  {
      std::cout << "Hello, C++!" << std::endl;

      return 0;
  }
EOF

  cat >"$name/CMakeLists.txt" <<EOF
cmake_minimum_required(VERSION 3.16)
project($name)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable($name
    src/main.cpp
)

target_compile_options($name PRIVATE
    -Wall
    -Wextra
    -Wpedantic
)
EOF

  echo -e "${GREEN}Projet C++ '$name' created !${NC}"
  echo -e "${RED}💡 tips : "
  echo -e "  ${RED}To build project"
  echo -e "    cd $name"
  echo -e "    cargopp build"
  echo -e "  ${RED}To run project main : "
  echo -e "    cd $name"
  echo -e "    cargopp run $name"
  echo -e "  ${RED}To run other bin script : "
  echo -e "    cd $name"
  echo -e "    cargopp run <script name>"

}
# cargopp run script

run_cargopp() {
  local name=$1 # start compilation

  build_cargopp
  if [ ! -f "build/$name" ]; then
    echo "❌ Error: Build/$name does not exist. Please run 'cargopp build' first."
    exit 1
  fi

  ./build/"$name"

}

## argument initialization

if [ "$#" -lt 1 ]; then
  echo "Usage: cargopp <command> [argument]"
  exit 1
fi

COMMAND="$1"

case "$COMMAND" in

new)
  if [ "$#" -ne 2 ]; then
    echo "Usage: cargopp new <project_name>"
    exit 1
  fi

  PROJECT="$2"
  new_cargopp "$PROJECT"
  ;;

build)
  build_cargopp
  ;;

run)
  if [ "$#" -ne 2 ]; then
    echo "Error: cargopp run requires a program name"
    echo "Usage: cargopp run <program_name>"
    exit 1
  fi

  FILENAME="$2"
  run_cargopp "$FILENAME"
  ;;

install)
  install_cargopp
  ;;

*)
  echo "Error: command '$COMMAND' not recognized."
  echo "Usage: cargopp <command> [argument]"
  echo ""
  echo "Commands:"
  echo "  install              Install cargopp globally"
  echo "  new <name>           Create a new C++ project"
  echo "  build                Build the current project"
  echo "  run <program>        Build and run a program"
  exit 2
  ;;

esac
