#! /usr/bin/env bash
set -euo pipefail
check_dependencies() {
  echo "🔍 Checking dependencies..."
  os="$1"
  missing_deps=()
  curl_absent=false
  if ! command -v cmake >/dev/null 2>&1; then
    missing_deps+=("cmake")
  fi

  if ! command -v g++ >/dev/null 2>&1 || ! command -v gcc >/dev/null 2>&1; then
    missing_deps+=("g++")
  fi

  if ! command -v curl >/dev/null 2>&1; then
    curl_absent=true
  fi

  # stop if everythink is good

  if [[ "${#missing_deps[@]}" -eq 0 && "$curl_absent" == false ]]; then
    return 0
  else
    install_curl=""
    if [ "$curl_absent" == true ]; then
      case "$os" in
      debian)
        install_curl="sudo apt install curl"
        ;;
      redhat)
        install_curl="sudo dnf install curl"
        ;;
      *)
        echo -e "${RED}❌ Unsupported OS template. Please install cmake and g++ manually.${NC}"
        return 1
        ;;
      esac
    fi

    if [ ! "${#missing_deps[@]}" -eq 0 ]; then
      echo -e "${YELLOW}⚠️ Missing required tools: ${missing_deps[*]}${NC}"
      install_cmd=""
      case "$os" in
      *debian*)
        install_cmd="sudo apt update && sudo apt install -y cmake build-essential"
        ;;
      *redhat*)
        install_cmd="sudo dnf update -y && sudo dnf group install -y 'Development Tools' && sudo dnf install -y cmake"
        ;;
      *)
        echo -e "${RED}❌ Unsupported OS template. Please install cmake and g++ manually.${NC}"
        return 1
        ;;
      esac
      if [ ! -z "$install_curl" ]; then
        install_cmd="$install_curl && $install_cmd"
      fi
    else
      install_cmd="$install_curl"
    fi
    echo -e "${BLUE}👉 cargopp can install them for you.${NC}"
    read -p "Do you want to run [ $install_cmd ] ? (Y/n): " response
    response=${response,,} # Convert to lowercase

    if [[ "$response" =~ ^(yes|y|"") ]]; then
      echo -e "${BLUE}⚙️ Installing dependencies...${NC}"
      eval "$install_cmd"
      if [ $? -ne 0 ]; then
        echo -e "${RED}❌ Error during dependencies installation.${NC}"
        return 1
      fi
      echo -e "${GREEN}✅ Dependencies installed successfully!${NC}"
    else
      echo -e "${RED}❌ Installation aborted. cargopp requires cmake and g++ to work.${NC}"
      return 1
    fi
  fi
}
