#!/bin/bash

# ---- COULEURS ANSI ----
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

REAL_USER="${SUDO_USER:-$USER}"
REAL_HOME=$(getent passwd "$REAL_USER" | cut -d: -f6)

# external scripts
fos="source '$REAL_HOME'/.cargopp/bin/lib/smart_update/tools/find_os"
cb="source '$REAL_HOME'/.cargopp/bin/lib/smart_update/tools/curl_bring"
cdep="source '$REAL_HOME'/.cargopp/bin/lib/smart_update/tools/check_dependencies"

manage_installation_deb_redhat() {
  echo "Installation of cargopp In the system.."
  # chech dependencies

  eval "$cdep" "$1" # check_dependencies
  user_position="$(pwd)"
  my_position="$REAL_HOME/.cargopp"
  cd "$my_position"
  # installing git repositories
  echo "⚙️ installing git repositories of cargopp.."
  cd bin
  cd lib
  eval "$cb"
  cd $user_position
  echo "cargopp updated with success!"
  exit 0
}

OS=$(eval "$fos")
case "$OS" in
*debian*)
  manage_installation_deb_redhat "$OS"
  ;;
*redhat*)
  manage_installation_deb_redhat "$OS"
  ;;
*)
  echo -e "${RED}❌ Unsupported OS template. Please install cmake and g++ manually.${NC}"
  exit 1
  ;;
esac
