#!/bin/bash

# external scripts

REAL_USER="${SUDO_USER:-$USER}"
REAL_HOME=$(getent passwd "$REAL_USER" | cut -d: -f6)
ROOT="$REAL_HOME/.cargopp"
#USERROOT=$(pwd)

source "$ROOT"/bin/lib/smart_update/fly
source "$ROOT"/bin/lib/paint
verify_owner() {
  local owner=$(ls -ld "$REAL_HOME/.cargopp" 2>/dev/null | awk '{print $3}')
  if [[ "$owner" != "$REAL_USER" ]]; then
    sudo chown -R "$REAL_USER:$REAL_USER" "$REAL_HOME/.cargopp"
  fi
}

## argument initialization
if [ "$#" -lt 1 ]; then
  echo "Usage: cargopp <command> [argument]"
  exit 1
fi
verify_owner
COMMAND="$1"

case "$COMMAND" in
new)
  fly

  if [ "$#" -lt 2 ]; then
    echo "Usage: cargopp new <project_name> [--c]"
    exit 1
  fi

  PROJECT="$2"

  if [ "$#" -eq 2 ]; then
    source "$ROOT"/bin/lib/new_cpp
    new_cpp "$PROJECT"
  elif [ "$#" -eq 3 ] && [ "$3" = "--c" ]; then
    source "$ROOT"/bin/lib/new_c
    new_c "$PROJECT"
  else
    echo "Usage: cargopp new <project_name> [--c]"
    exit 1
  fi
  ;;

build)
  fly
  source "$ROOT"/bin/lib/build_cargopp
  build_cargopp
  ;;

run)
  fly
  if [ "$#" -ne 2 ]; then
    echo "Error: cargopp run requires a program name"
    echo "Usage: cargopp run <program_name>"
    echo -e "Use <cargopp --help --run> to see in particular how to use correctly cargopp run"
    exit 1
  fi
  source "$ROOT"/bin/lib/run
  FILENAME="$2"
  shift 2
  number_arg="$#"
  if [[ "$number_arg" -gt 0 ]]; then
    arguments=$@
    run "$FILENAME" $arguments
  else
    run "$FILENAME"
  fi
  ;;
update)
  source "$ROOT"/bin/lib/smart_update/update
  update
  ;;
--version | version)
  fly
  echo $(cat "$ROOT"/cargopp_version)
  ;;
--uninstall | uninstall)
  source "$ROOT"/bin/lib/uninstall
  uninstall
  ;;
--help)
  source "$ROOT"/bin/lib/help/help
  arguments=$@
  help $arguments
  ;;
clean)
  source "$ROOT"/bin/lib/clean
  clean
  ;;
*)
  echo "Error: command '$COMMAND' not recognized."
  echo "Use cargopp --help               To see all cargopp's commands and their utility"
  exit 2
  ;;

esac
